# Generated by Django 3.1.4 on 2020-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201219_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='desc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
