# Generated by Django 3.1.4 on 2020-12-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201219_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default=2, max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
    ]
