# Generated by Django 3.1.4 on 2020-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201219_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین اپدیت'),
        ),
    ]
