# Generated by Django 3.1.4 on 2020-12-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_last_update'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'title')},
        ),
    ]
