# Generated by Django 3.1.4 on 2020-12-24 19:26

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_uniq_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=post.models.LowercaseEmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
