# Generated by Django 3.1.4 on 2020-12-27 12:14

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20201224_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=post.models.LowercaseEmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
