# Generated by Django 3.1.4 on 2020-12-28 14:52

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20201227_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=post.models.LowercaseEmailField(blank=True, default=None, max_length=254, unique=True),
        ),
    ]
