# Generated by Django 3.1.4 on 2020-12-28 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20201228_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_date_sent_mail',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
