# Generated by Django 3.1.4 on 2020-12-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20201229_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, height_field=20, null=True, upload_to='images/%Y/%m/%d', verbose_name='تصویر', width_field=40),
        ),
    ]
