# Generated by Django 3.1.4 on 2020-12-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20201229_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='تصویر'),
        ),
    ]
