# Generated by Django 3.1.4 on 2020-12-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20201229_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_date_sent_mail',
            field=models.DateTimeField(auto_now_add=True, db_column='date_sent'),
        ),
    ]
