# Generated by Django 3.1.4 on 2020-12-29 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20201230_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_date_sent_mail',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, db_column='last_date_sent_mail', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
